previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    name: mensaje-web
    env: node
    plan: standard
    previewPlan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz prisma migrate deploy --preview-feature && blitz build
    # If you have an out of memory error, change startCommand to "yarn next start"
    startCommand: blitz start
    afterFirstDeployCommand: blitz db seed
    envVars:
      - key: NODE_ENV
        value: production
        previewValue: production
      - key: DATABASE_URL
        fromDatabase:
          name: mensaje-db
          property: connectionString
      - fromGroup: mensaje

databases:
  - name: mensaje-db
    plan: standard
    previewPlan: starter
